// Generated by scripts/generate-online-schema.py.
import { Column, Entity } from 'typeorm';
import { OnlineBaseEntity } from './online-base.entity';

@Entity({ name: 'order_prescriptions' })
export class OrderPrescriptions extends OnlineBaseEntity {
  @Column({ name: 'order_id', type: 'char', length: 36 })
  orderId!: string;

  @Column({ name: 'order_line_id', type: 'char', length: 36, nullable: true })
  orderLineId!: string | null;

  @Column({ name: 'file_storage_key', type: 'varchar', length: 512 })
  fileStorageKey!: string;

  @Column({ name: 'file_name', type: 'varchar', length: 255 })
  fileName!: string;

  @Column({ name: 'mime_type', type: 'varchar', length: 128 })
  mimeType!: string;

  @Column({ name: 'status', type: 'varchar', length: 32, default: "PENDING" })
  status!: string;

  @Column({ name: 'reviewed_by', type: 'char', length: 36, nullable: true })
  reviewedBy!: string | null;

  @Column({ name: 'reviewed_at', type: 'datetime', precision: 6, nullable: true })
  reviewedAt!: Date | null;

  @Column({ name: 'rejection_reason', type: 'varchar', length: 1000, nullable: true })
  rejectionReason!: string | null;

}
