// Generated by scripts/generate-online-schema.py.
import { Column, Entity } from 'typeorm';
import { OnlineBaseEntity } from './online-base.entity';

@Entity({ name: 'order_events' })
export class OrderEvents extends OnlineBaseEntity {
  @Column({ name: 'order_id', type: 'char', length: 36 })
  orderId!: string;

  @Column({ name: 'from_status', type: 'varchar', length: 32, nullable: true })
  fromStatus!: string | null;

  @Column({ name: 'to_status', type: 'varchar', length: 32 })
  toStatus!: string;

  @Column({ name: 'actor_type', type: 'varchar', length: 32 })
  actorType!: string;

  @Column({ name: 'actor_user_id', type: 'char', length: 36, nullable: true })
  actorUserId!: string | null;

  @Column({ name: 'actor_customer_id', type: 'char', length: 36, nullable: true })
  actorCustomerId!: string | null;

  @Column({ name: 'note', type: 'varchar', length: 1000, nullable: true })
  note!: string | null;

}
