// Generated by scripts/generate-online-schema.py.
import { Column, Entity } from 'typeorm';
import { OnlineBaseEntity } from './online-base.entity';

@Entity({ name: 'payment_attempts' })
export class PaymentAttempts extends OnlineBaseEntity {
  @Column({ name: 'order_id', type: 'char', length: 36 })
  orderId!: string;

  @Column({ name: 'provider', type: 'varchar', length: 64 })
  provider!: string;

  @Column({ name: 'payment_method', type: 'varchar', length: 32 })
  paymentMethod!: string;

  @Column({ name: 'provider_request_id', type: 'varchar', length: 191, nullable: true })
  providerRequestId!: string | null;

  @Column({ name: 'provider_transaction_id', type: 'varchar', length: 191, nullable: true })
  providerTransactionId!: string | null;

  @Column({ name: 'idempotency_key', type: 'varchar', length: 128 })
  idempotencyKey!: string;

  @Column({ name: 'amount', type: 'decimal', precision: 19, scale: 4 })
  amount!: string;

  @Column({ name: 'refunded_amount', type: 'decimal', precision: 19, scale: 4, default: 0 })
  refundedAmount!: string;

  @Column({ name: 'currency', type: 'char', length: 3, default: "VND" })
  currency!: string;

  @Column({ name: 'status', type: 'varchar', length: 32, default: "INITIATED" })
  status!: string;

  @Column({ name: 'requested_at', type: 'datetime', precision: 6, default: () => 'CURRENT_TIMESTAMP(6)' })
  requestedAt!: Date;

  @Column({ name: 'finalized_at', type: 'datetime', precision: 6, nullable: true })
  finalizedAt!: Date | null;

}
