// Generated by scripts/generate-online-schema.py.
import { Column, Entity } from 'typeorm';
import { OnlineBaseEntity } from './online-base.entity';

@Entity({ name: 'shipments' })
export class Shipments extends OnlineBaseEntity {
  @Column({ name: 'order_id', type: 'char', length: 36 })
  orderId!: string;

  @Column({ name: 'carrier', type: 'varchar', length: 64, nullable: true })
  carrier!: string | null;

  @Column({ name: 'tracking_number', type: 'varchar', length: 191, nullable: true })
  trackingNumber!: string | null;

  @Column({ name: 'status', type: 'varchar', length: 32, default: "PENDING" })
  status!: string;

  @Column({ name: 'shipped_at', type: 'datetime', precision: 6, nullable: true })
  shippedAt!: Date | null;

  @Column({ name: 'delivered_at', type: 'datetime', precision: 6, nullable: true })
  deliveredAt!: Date | null;

  @Column({ name: 'delivery_note', type: 'varchar', length: 1000, nullable: true })
  deliveryNote!: string | null;

}
