// Generated by scripts/generate-online-schema.py.
import { Column, Entity } from 'typeorm';
import { OnlineBaseEntity } from './online-base.entity';

@Entity({ name: 'carts' })
export class Carts extends OnlineBaseEntity {
  @Column({ name: 'customer_id', type: 'char', length: 36 })
  customerId!: string;

  @Column({ name: 'branch_id', type: 'char', length: 36, nullable: true })
  branchId!: string | null;

  @Column({ name: 'status', type: 'varchar', length: 32, default: "ACTIVE" })
  status!: string;

  @Column({ name: 'expires_at', type: 'datetime', precision: 6, nullable: true })
  expiresAt!: Date | null;

  @Column({ name: 'version', type: 'bigint', unsigned: true, default: 0 })
  version!: string;

  @Column({ name: 'active_customer_key', type: 'char', length: 36, nullable: true, asExpression: "CASE WHEN `status` = 'ACTIVE' THEN `customer_id` ELSE NULL END", generatedType: 'STORED', insert: false, update: false })
  activeCustomerKey!: string | null;

}
