// Generated by scripts/generate-online-schema.py.
import { Column, Entity } from 'typeorm';
import { OnlineBaseEntity } from './online-base.entity';

@Entity({ name: 'customer_accounts' })
export class CustomerAccounts extends OnlineBaseEntity {
  @Column({ name: 'customer_id', type: 'char', length: 36 })
  customerId!: string;

  @Column({ name: 'auth_provider', type: 'varchar', length: 32 })
  authProvider!: string;

  @Column({ name: 'provider_subject', type: 'varchar', length: 191 })
  providerSubject!: string;

  @Column({ name: 'email', type: 'varchar', length: 255, nullable: true })
  email!: string | null;

  @Column({ name: 'email_verified_at', type: 'datetime', precision: 6, nullable: true })
  emailVerifiedAt!: Date | null;

  @Column({ name: 'phone_verified_at', type: 'datetime', precision: 6, nullable: true })
  phoneVerifiedAt!: Date | null;

  @Column({ name: 'status', type: 'varchar', length: 32, default: "ACTIVE" })
  status!: string;

}
