// Generated by scripts/generate-online-schema.py.
import { Column, Entity } from 'typeorm';
import { OnlineBaseEntity } from './online-base.entity';

@Entity({ name: 'customer_addresses' })
export class CustomerAddresses extends OnlineBaseEntity {
  @Column({ name: 'customer_id', type: 'char', length: 36 })
  customerId!: string;

  @Column({ name: 'label', type: 'varchar', length: 64, nullable: true })
  label!: string | null;

  @Column({ name: 'recipient_name', type: 'varchar', length: 255 })
  recipientName!: string;

  @Column({ name: 'recipient_phone', type: 'varchar', length: 32 })
  recipientPhone!: string;

  @Column({ name: 'address_line1', type: 'varchar', length: 500 })
  addressLine1!: string;

  @Column({ name: 'address_line2', type: 'varchar', length: 500, nullable: true })
  addressLine2!: string | null;

  @Column({ name: 'ward', type: 'varchar', length: 128, nullable: true })
  ward!: string | null;

  @Column({ name: 'district', type: 'varchar', length: 128, nullable: true })
  district!: string | null;

  @Column({ name: 'province', type: 'varchar', length: 128 })
  province!: string;

  @Column({ name: 'postal_code', type: 'varchar', length: 32, nullable: true })
  postalCode!: string | null;

  @Column({ name: 'country_code', type: 'char', length: 2, default: "VN" })
  countryCode!: string;

  @Column({ name: 'is_default', type: 'tinyint', default: 0 })
  isDefault!: boolean;

  @Column({ name: 'default_customer_key', type: 'char', length: 36, nullable: true, asExpression: "CASE WHEN `is_default` = 1 THEN `customer_id` ELSE NULL END", generatedType: 'STORED', insert: false, update: false })
  defaultCustomerKey!: string | null;

}
