// Generated by scripts/generate-online-schema.py.
import { Column, Entity } from 'typeorm';
import { OnlineBaseEntity } from './online-base.entity';

@Entity({ name: 'orders' })
export class Orders extends OnlineBaseEntity {
  @Column({ name: 'customer_id', type: 'char', length: 36 })
  customerId!: string;

  @Column({ name: 'branch_id', type: 'char', length: 36 })
  branchId!: string;

  @Column({ name: 'warehouse_id', type: 'char', length: 36 })
  warehouseId!: string;

  @Column({ name: 'cart_id', type: 'char', length: 36, nullable: true })
  cartId!: string | null;

  @Column({ name: 'order_number', type: 'varchar', length: 64 })
  orderNumber!: string;

  @Column({ name: 'idempotency_key', type: 'varchar', length: 128 })
  idempotencyKey!: string;

  @Column({ name: 'status', type: 'varchar', length: 32, default: "PLACED" })
  status!: string;

  @Column({ name: 'payment_status', type: 'varchar', length: 32, default: "UNPAID" })
  paymentStatus!: string;

  @Column({ name: 'review_status', type: 'varchar', length: 32, default: "NOT_REQUIRED" })
  reviewStatus!: string;

  @Column({ name: 'reviewed_by', type: 'char', length: 36, nullable: true })
  reviewedBy!: string | null;

  @Column({ name: 'reviewed_at', type: 'datetime', precision: 6, nullable: true })
  reviewedAt!: Date | null;

  @Column({ name: 'fulfillment_method', type: 'varchar', length: 32 })
  fulfillmentMethod!: string;

  @Column({ name: 'currency', type: 'char', length: 3, default: "VND" })
  currency!: string;

  @Column({ name: 'subtotal', type: 'decimal', precision: 19, scale: 4, default: 0 })
  subtotal!: string;

  @Column({ name: 'discount_amount', type: 'decimal', precision: 19, scale: 4, default: 0 })
  discountAmount!: string;

  @Column({ name: 'tax_amount', type: 'decimal', precision: 19, scale: 4, default: 0 })
  taxAmount!: string;

  @Column({ name: 'shipping_fee', type: 'decimal', precision: 19, scale: 4, default: 0 })
  shippingFee!: string;

  @Column({ name: 'total_amount', type: 'decimal', precision: 19, scale: 4, default: 0 })
  totalAmount!: string;

  @Column({ name: 'recipient_name', type: 'varchar', length: 255, nullable: true })
  recipientName!: string | null;

  @Column({ name: 'recipient_phone', type: 'varchar', length: 32, nullable: true })
  recipientPhone!: string | null;

  @Column({ name: 'shipping_address_line1', type: 'varchar', length: 500, nullable: true })
  shippingAddressLine1!: string | null;

  @Column({ name: 'shipping_address_line2', type: 'varchar', length: 500, nullable: true })
  shippingAddressLine2!: string | null;

  @Column({ name: 'shipping_ward', type: 'varchar', length: 128, nullable: true })
  shippingWard!: string | null;

  @Column({ name: 'shipping_district', type: 'varchar', length: 128, nullable: true })
  shippingDistrict!: string | null;

  @Column({ name: 'shipping_province', type: 'varchar', length: 128, nullable: true })
  shippingProvince!: string | null;

  @Column({ name: 'shipping_postal_code', type: 'varchar', length: 32, nullable: true })
  shippingPostalCode!: string | null;

  @Column({ name: 'shipping_country_code', type: 'char', length: 2, nullable: true })
  shippingCountryCode!: string | null;

  @Column({ name: 'sale_id', type: 'char', length: 36, nullable: true })
  saleId!: string | null;

  @Column({ name: 'placed_at', type: 'datetime', precision: 6 })
  placedAt!: Date;

  @Column({ name: 'confirmed_at', type: 'datetime', precision: 6, nullable: true })
  confirmedAt!: Date | null;

  @Column({ name: 'completed_at', type: 'datetime', precision: 6, nullable: true })
  completedAt!: Date | null;

  @Column({ name: 'cancelled_at', type: 'datetime', precision: 6, nullable: true })
  cancelledAt!: Date | null;

}
