// Generated by scripts/generate-online-schema.py.
import { Column, Entity } from 'typeorm';
import { OnlineBaseEntity } from './online-base.entity';

@Entity({ name: 'order_discounts' })
export class OrderDiscounts extends OnlineBaseEntity {
  @Column({ name: 'order_id', type: 'char', length: 36 })
  orderId!: string;

  @Column({ name: 'order_line_id', type: 'char', length: 36, nullable: true })
  orderLineId!: string | null;

  @Column({ name: 'promotion_id', type: 'char', length: 36, nullable: true })
  promotionId!: string | null;

  @Column({ name: 'promotion_product_id', type: 'char', length: 36, nullable: true })
  promotionProductId!: string | null;

  @Column({ name: 'code_snapshot', type: 'varchar', length: 64 })
  codeSnapshot!: string;

  @Column({ name: 'amount', type: 'decimal', precision: 19, scale: 4 })
  amount!: string;

}
