// Generated by scripts/generate-online-schema.py.
import { Column, Entity } from 'typeorm';
import { OnlineBaseEntity } from './online-base.entity';

@Entity({ name: 'product_listings' })
export class ProductListings extends OnlineBaseEntity {
  @Column({ name: 'product_id', type: 'char', length: 36 })
  productId!: string;

  @Column({ name: 'slug', type: 'varchar', length: 191 })
  slug!: string;

  @Column({ name: 'title', type: 'varchar', length: 255 })
  title!: string;

  @Column({ name: 'description', type: 'text', nullable: true })
  description!: string | null;

  @Column({ name: 'image_storage_key', type: 'varchar', length: 512, nullable: true })
  imageStorageKey!: string | null;

  @Column({ name: 'status', type: 'varchar', length: 32, default: "DRAFT" })
  status!: string;

  @Column({ name: 'published_at', type: 'datetime', precision: 6, nullable: true })
  publishedAt!: Date | null;

}
