// Generated from pharmacy_pos_inventory_mysql_spec.md by scripts/generate-schema.py.
import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1700000000000 implements MigrationInterface {
  name = 'InitialSchema1700000000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("CREATE TABLE `organizations` (\n  `id` CHAR(36) NOT NULL,\n  `code` VARCHAR(64) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_organizations_01` UNIQUE (`code`),\n  CONSTRAINT `ck_organizations_status` CHECK (`status` IN ('ACTIVE', 'INACTIVE'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_organizations_status` ON `organizations` (`status`)');
    await queryRunner.query("CREATE TABLE `branches` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `code` VARCHAR(64) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `address` VARCHAR(500) NULL DEFAULT NULL,\n  `phone` VARCHAR(32) NULL DEFAULT NULL,\n  `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_branches_01` UNIQUE (`organization_id`, `code`),\n  CONSTRAINT `ck_branches_status` CHECK (`status` IN ('ACTIVE', 'INACTIVE'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_branches_org_status` ON `branches` (`organization_id`, `status`)');
    await queryRunner.query("CREATE TABLE `warehouses` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NULL DEFAULT NULL,\n  `code` VARCHAR(64) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `warehouse_type` VARCHAR(32) NOT NULL DEFAULT 'SALE',\n  `allow_sale` TINYINT(1) NOT NULL DEFAULT 0,\n  `allow_negative_stock` TINYINT(1) NOT NULL DEFAULT 0,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_warehouses_01` UNIQUE (`organization_id`, `code`),\n  CONSTRAINT `ck_warehouses_warehouse_type` CHECK (`warehouse_type` IN ('SALE', 'RESERVE', 'RETURN', 'QUARANTINE', 'DAMAGED', 'TRANSIT', 'CENTRAL'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_warehouses_branch` ON `warehouses` (`branch_id`, `status`)');
    await queryRunner.query('CREATE INDEX `idx_warehouses_org_type` ON `warehouses` (`organization_id`, `warehouse_type`)');
    await queryRunner.query("CREATE TABLE `stock_locations` (\n  `id` CHAR(36) NOT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `code` VARCHAR(64) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `location_type` VARCHAR(32) NOT NULL DEFAULT 'STORAGE',\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_stock_locations_01` UNIQUE (`warehouse_id`, `code`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_stock_locations_wh_status` ON `stock_locations` (`warehouse_id`, `status`)');
    await queryRunner.query("CREATE TABLE `users` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `username` VARCHAR(128) NOT NULL,\n  `full_name` VARCHAR(255) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_users_01` UNIQUE (`organization_id`, `username`),\n  CONSTRAINT `ck_users_status` CHECK (`status` IN ('ACTIVE', 'LOCKED', 'INACTIVE'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_users_org_status` ON `users` (`organization_id`, `status`)');
    await queryRunner.query('CREATE TABLE `roles` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `code` VARCHAR(64) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_roles_01` UNIQUE (`organization_id`, `code`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE TABLE `permissions` (\n  `id` CHAR(36) NOT NULL,\n  `code` VARCHAR(128) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_permissions_01` UNIQUE (`code`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE TABLE `user_roles` (\n  `id` CHAR(36) NOT NULL,\n  `user_id` CHAR(36) NOT NULL,\n  `role_id` CHAR(36) NOT NULL,\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_user_roles_01` UNIQUE (`user_id`, `role_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_user_roles_role` ON `user_roles` (`role_id`, `user_id`)');
    await queryRunner.query('CREATE TABLE `role_permissions` (\n  `id` CHAR(36) NOT NULL,\n  `role_id` CHAR(36) NOT NULL,\n  `permission_id` CHAR(36) NOT NULL,\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_role_permissions_01` UNIQUE (`role_id`, `permission_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE TABLE `user_branch_access` (\n  `id` CHAR(36) NOT NULL,\n  `user_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NOT NULL,\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_user_branch_access_01` UNIQUE (`user_id`, `branch_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE TABLE `categories` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `parent_id` CHAR(36) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_categories_org_parent` ON `categories` (`organization_id`, `parent_id`)');
    await queryRunner.query('CREATE TABLE `manufacturers` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `country` VARCHAR(128) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_manufacturers_01` UNIQUE (`organization_id`, `name`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE TABLE `units` (\n  `id` CHAR(36) NOT NULL,\n  `code` VARCHAR(32) NOT NULL,\n  `name` VARCHAR(128) NOT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_units_01` UNIQUE (`code`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query("CREATE TABLE `products` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `sku` VARCHAR(64) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `short_name` VARCHAR(255) NULL DEFAULT NULL,\n  `category_id` CHAR(36) NULL DEFAULT NULL,\n  `manufacturer_id` CHAR(36) NULL DEFAULT NULL,\n  `product_type` VARCHAR(32) NOT NULL DEFAULT 'MEDICINE',\n  `active_ingredient` VARCHAR(500) NULL DEFAULT NULL,\n  `strength` VARCHAR(128) NULL DEFAULT NULL,\n  `dosage_form` VARCHAR(128) NULL DEFAULT NULL,\n  `registration_number` VARCHAR(128) NULL DEFAULT NULL,\n  `prescription_type` VARCHAR(32) NULL DEFAULT NULL,\n  `track_lot` TINYINT(1) NOT NULL DEFAULT 1,\n  `track_expiry` TINYINT(1) NOT NULL DEFAULT 1,\n  `base_unit_id` CHAR(36) NOT NULL,\n  `vat_rate` DECIMAL(9,4) NOT NULL DEFAULT 0,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_products_01` UNIQUE (`organization_id`, `sku`),\n  CONSTRAINT `ck_products_01` CHECK (vat_rate >= 0),\n  CONSTRAINT `ck_products_product_type` CHECK (`product_type` IN ('MEDICINE', 'SUPPLEMENT', 'COSMETIC', 'DEVICE', 'OTHER')),\n  CONSTRAINT `ck_products_prescription_type` CHECK (`prescription_type` IN ('RX', 'OTC', 'OTHER'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_products_org_name` ON `products` (`organization_id`, `name`)');
    await queryRunner.query('CREATE INDEX `idx_products_org_category` ON `products` (`organization_id`, `category_id`, `status`)');
    await queryRunner.query('CREATE INDEX `idx_products_registration` ON `products` (`organization_id`, `registration_number`)');
    await queryRunner.query('CREATE TABLE `product_units` (\n  `id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `unit_id` CHAR(36) NOT NULL,\n  `conversion_factor` DECIMAL(20,6) NOT NULL DEFAULT 1,\n  `is_base_unit` TINYINT(1) NOT NULL DEFAULT 0,\n  `allow_purchase` TINYINT(1) NOT NULL DEFAULT 1,\n  `allow_sale` TINYINT(1) NOT NULL DEFAULT 1,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_product_units_01` UNIQUE (`product_id`, `unit_id`),\n  CONSTRAINT `ck_product_units_01` CHECK (conversion_factor > 0)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_product_units_product` ON `product_units` (`product_id`, `allow_sale`, `allow_purchase`)');
    await queryRunner.query("CREATE TABLE `product_barcodes` (\n  `id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `product_unit_id` CHAR(36) NULL DEFAULT NULL,\n  `barcode` VARCHAR(128) NOT NULL,\n  `barcode_type` VARCHAR(32) NULL DEFAULT NULL,\n  `is_primary` TINYINT(1) NOT NULL DEFAULT 0,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_product_barcodes_01` UNIQUE (`product_id`, `barcode`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_product_barcodes_lookup` ON `product_barcodes` (`barcode`, `status`)');
    await queryRunner.query('CREATE INDEX `idx_product_barcodes_unit` ON `product_barcodes` (`product_unit_id`)');
    await queryRunner.query("CREATE TABLE `suppliers` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `code` VARCHAR(64) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `phone` VARCHAR(32) NULL DEFAULT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_suppliers_01` UNIQUE (`organization_id`, `code`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_suppliers_org_name` ON `suppliers` (`organization_id`, `name`)');
    await queryRunner.query("CREATE TABLE `customers` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `code` VARCHAR(64) NULL DEFAULT NULL,\n  `name` VARCHAR(255) NULL DEFAULT NULL,\n  `phone` VARCHAR(32) NULL DEFAULT NULL,\n  `customer_group` VARCHAR(64) NULL DEFAULT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_customers_01` UNIQUE (`organization_id`, `code`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_customers_phone` ON `customers` (`organization_id`, `phone`)');
    await queryRunner.query('CREATE INDEX `idx_customers_name` ON `customers` (`organization_id`, `name`)');
    await queryRunner.query("CREATE TABLE `inventory_lots` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `batch_number` VARCHAR(128) NOT NULL,\n  `manufacturing_date` DATE NULL DEFAULT NULL,\n  `expiry_date` DATE NULL DEFAULT NULL,\n  `manufacturer_id` CHAR(36) NULL DEFAULT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_inventory_lots_01` UNIQUE (`organization_id`, `product_id`, `batch_number`),\n  CONSTRAINT `ck_inventory_lots_01` CHECK (expiry_date IS NULL OR manufacturing_date IS NULL OR expiry_date >= manufacturing_date),\n  CONSTRAINT `ck_inventory_lots_status` CHECK (`status` IN ('ACTIVE', 'BLOCKED', 'QUARANTINED', 'CLOSED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_lots_product_expiry` ON `inventory_lots` (`product_id`, `status`, `expiry_date`)');
    await queryRunner.query('CREATE INDEX `idx_lots_org_expiry` ON `inventory_lots` (`organization_id`, `expiry_date`, `status`)');
    await queryRunner.query("CREATE TABLE `inventory_movements` (\n  `id` CHAR(36) NOT NULL,\n  `ledger_seq` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n  `organization_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NULL DEFAULT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `location_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `lot_id` CHAR(36) NOT NULL,\n  `movement_type` VARCHAR(32) NOT NULL,\n  `quantity_delta` DECIMAL(20,6) NOT NULL,\n  `unit_cost` DECIMAL(19,4) NULL DEFAULT NULL,\n  `source_type` VARCHAR(64) NOT NULL,\n  `source_id` CHAR(36) NOT NULL,\n  `source_line_id` CHAR(36) NULL DEFAULT NULL,\n  `reference_no` VARCHAR(128) NULL DEFAULT NULL,\n  `occurred_at` DATETIME(6) NOT NULL,\n  `posted_at` DATETIME(6) NOT NULL,\n  `created_by` CHAR(36) NULL DEFAULT NULL,\n  `device_id` CHAR(36) NULL DEFAULT NULL,\n  `idempotency_key` VARCHAR(128) NULL DEFAULT NULL,\n  `reversal_of_id` CHAR(36) NULL DEFAULT NULL,\n  `note` VARCHAR(1000) NULL DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_inventory_movements_ledger_seq` UNIQUE (`ledger_seq`),\n  CONSTRAINT `uq_inventory_movements_01` UNIQUE (`ledger_seq`),\n  CONSTRAINT `ck_inventory_movements_01` CHECK (quantity_delta <> 0),\n  CONSTRAINT `ck_inventory_movements_movement_type` CHECK (`movement_type` IN ('PURCHASE_RECEIPT', 'SUPPLIER_RETURN', 'SALE', 'SALE_RETURN', 'TRANSFER_OUT', 'TRANSFER_TRANSIT_IN', 'TRANSFER_TRANSIT_OUT', 'TRANSFER_IN', 'STOCK_ADJUSTMENT', 'COUNT_ADJUSTMENT', 'DAMAGE', 'EXPIRY', 'REVERSAL', 'INTERNAL_USE', 'SAMPLE'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_movements_balance` ON `inventory_movements` (`warehouse_id`, `location_id`, `product_id`, `lot_id`, `ledger_seq`)');
    await queryRunner.query('CREATE INDEX `idx_movements_product_time` ON `inventory_movements` (`organization_id`, `product_id`, `occurred_at`)');
    await queryRunner.query('CREATE INDEX `idx_movements_source` ON `inventory_movements` (`source_type`, `source_id`, `source_line_id`)');
    await queryRunner.query('CREATE INDEX `idx_movements_reference` ON `inventory_movements` (`organization_id`, `reference_no`)');
    await queryRunner.query('CREATE INDEX `idx_movements_reversal` ON `inventory_movements` (`reversal_of_id`)');
    await queryRunner.query('CREATE INDEX `idx_movements_posted` ON `inventory_movements` (`organization_id`, `posted_at`, `ledger_seq`)');
    await queryRunner.query('CREATE TABLE `inventory_balances` (\n  `organization_id` CHAR(36) NOT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `location_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `lot_id` CHAR(36) NOT NULL,\n  `on_hand_qty` DECIMAL(20,6) NOT NULL DEFAULT 0,\n  `reserved_qty` DECIMAL(20,6) NOT NULL DEFAULT 0,\n  `updated_at` DATETIME(6) NOT NULL,\n  `version` BIGINT UNSIGNED NOT NULL DEFAULT 0,\n  PRIMARY KEY (`organization_id`, `warehouse_id`, `location_id`, `product_id`, `lot_id`),\n  CONSTRAINT `ck_inventory_balances_01` CHECK (reserved_qty >= 0)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_balances_product_wh` ON `inventory_balances` (`product_id`, `warehouse_id`, `lot_id`)');
    await queryRunner.query('CREATE INDEX `idx_balances_wh_product` ON `inventory_balances` (`warehouse_id`, `product_id`)');
    await queryRunner.query('CREATE INDEX `idx_balances_lot` ON `inventory_balances` (`lot_id`, `warehouse_id`)');
    await queryRunner.query("CREATE TABLE `inventory_reservations` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `location_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `lot_id` CHAR(36) NOT NULL,\n  `reserved_qty` DECIMAL(20,6) NOT NULL,\n  `source_type` VARCHAR(64) NOT NULL,\n  `source_id` CHAR(36) NOT NULL,\n  `expires_at` DATETIME(6) NULL DEFAULT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_inventory_reservations_01` UNIQUE (`source_type`, `source_id`, `warehouse_id`, `location_id`, `product_id`, `lot_id`),\n  CONSTRAINT `ck_inventory_reservations_01` CHECK (reserved_qty > 0),\n  CONSTRAINT `ck_inventory_reservations_status` CHECK (`status` IN ('ACTIVE', 'CONSUMED', 'RELEASED', 'EXPIRED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_reservations_expiry` ON `inventory_reservations` (`status`, `expires_at`)');
    await queryRunner.query('CREATE INDEX `idx_reservations_balance` ON `inventory_reservations` (`warehouse_id`, `location_id`, `product_id`, `lot_id`, `status`)');
    await queryRunner.query("CREATE TABLE `purchase_orders` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NOT NULL,\n  `supplier_id` CHAR(36) NOT NULL,\n  `po_number` VARCHAR(64) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',\n  `ordered_at` DATETIME(6) NULL DEFAULT NULL,\n  `created_by` CHAR(36) NOT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_purchase_orders_01` UNIQUE (`organization_id`, `po_number`),\n  CONSTRAINT `ck_purchase_orders_status` CHECK (`status` IN ('DRAFT', 'APPROVED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_po_supplier_status` ON `purchase_orders` (`supplier_id`, `status`, `ordered_at`)');
    await queryRunner.query('CREATE INDEX `idx_po_branch_status` ON `purchase_orders` (`branch_id`, `status`, `ordered_at`)');
    await queryRunner.query('CREATE TABLE `purchase_order_lines` (\n  `id` CHAR(36) NOT NULL,\n  `purchase_order_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `product_unit_id` CHAR(36) NOT NULL,\n  `quantity` DECIMAL(20,6) NOT NULL,\n  `conversion_factor` DECIMAL(20,6) NOT NULL,\n  `base_quantity` DECIMAL(20,6) NOT NULL,\n  `unit_price` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `discount_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `tax_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `line_total` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `ck_purchase_order_lines_01` CHECK (quantity > 0),\n  CONSTRAINT `ck_purchase_order_lines_02` CHECK (conversion_factor > 0),\n  CONSTRAINT `ck_purchase_order_lines_03` CHECK (base_quantity > 0)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_po_lines_po` ON `purchase_order_lines` (`purchase_order_id`)');
    await queryRunner.query('CREATE INDEX `idx_po_lines_product` ON `purchase_order_lines` (`product_id`)');
    await queryRunner.query("CREATE TABLE `goods_receipts` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NOT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `supplier_id` CHAR(36) NOT NULL,\n  `purchase_order_id` CHAR(36) NULL DEFAULT NULL,\n  `receipt_number` VARCHAR(64) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',\n  `received_at` DATETIME(6) NOT NULL,\n  `posted_at` DATETIME(6) NULL DEFAULT NULL,\n  `created_by` CHAR(36) NOT NULL,\n  `idempotency_key` VARCHAR(128) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_goods_receipts_01` UNIQUE (`organization_id`, `receipt_number`),\n  CONSTRAINT `uq_goods_receipts_02` UNIQUE (`organization_id`, `idempotency_key`),\n  CONSTRAINT `ck_goods_receipts_status` CHECK (`status` IN ('DRAFT', 'APPROVED', 'POSTED', 'CANCELLED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_gr_wh_status` ON `goods_receipts` (`warehouse_id`, `status`, `received_at`)');
    await queryRunner.query('CREATE INDEX `idx_gr_po` ON `goods_receipts` (`purchase_order_id`)');
    await queryRunner.query('CREATE INDEX `idx_gr_supplier` ON `goods_receipts` (`supplier_id`, `received_at`)');
    await queryRunner.query('CREATE TABLE `goods_receipt_lines` (\n  `id` CHAR(36) NOT NULL,\n  `goods_receipt_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `product_unit_id` CHAR(36) NOT NULL,\n  `quantity` DECIMAL(20,6) NOT NULL,\n  `conversion_factor` DECIMAL(20,6) NOT NULL,\n  `base_quantity` DECIMAL(20,6) NOT NULL,\n  `lot_id` CHAR(36) NOT NULL,\n  `purchase_price` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `discount_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `tax_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `line_total` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `net_cost` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `ck_goods_receipt_lines_01` CHECK (quantity > 0),\n  CONSTRAINT `ck_goods_receipt_lines_02` CHECK (base_quantity > 0)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_gr_lines_receipt` ON `goods_receipt_lines` (`goods_receipt_id`)');
    await queryRunner.query('CREATE INDEX `idx_gr_lines_product_lot` ON `goods_receipt_lines` (`product_id`, `lot_id`)');
    await queryRunner.query("CREATE TABLE `pos_devices` (\n  `id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NOT NULL,\n  `code` VARCHAR(64) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_pos_devices_01` UNIQUE (`branch_id`, `code`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query("CREATE TABLE `pos_shifts` (\n  `id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NOT NULL,\n  `pos_device_id` CHAR(36) NOT NULL,\n  `opened_by` CHAR(36) NOT NULL,\n  `opened_at` DATETIME(6) NOT NULL,\n  `closed_at` DATETIME(6) NULL DEFAULT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'OPEN',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `ck_pos_shifts_status` CHECK (`status` IN ('OPEN', 'CLOSED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_pos_shifts_device_status` ON `pos_shifts` (`pos_device_id`, `status`, `opened_at`)');
    await queryRunner.query("CREATE TABLE `sales` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NOT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `sale_number` VARCHAR(64) NOT NULL,\n  `customer_id` CHAR(36) NULL DEFAULT NULL,\n  `subtotal` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `discount_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `tax_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `total_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',\n  `sold_at` DATETIME(6) NULL DEFAULT NULL,\n  `created_by` CHAR(36) NOT NULL,\n  `pos_device_id` CHAR(36) NULL DEFAULT NULL,\n  `shift_id` CHAR(36) NULL DEFAULT NULL,\n  `idempotency_key` VARCHAR(128) NOT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_sales_01` UNIQUE (`organization_id`, `sale_number`),\n  CONSTRAINT `uq_sales_02` UNIQUE (`organization_id`, `idempotency_key`),\n  CONSTRAINT `ck_sales_01` CHECK (total_amount >= 0),\n  CONSTRAINT `ck_sales_status` CHECK (`status` IN ('DRAFT', 'COMPLETED', 'VOIDED', 'PARTIALLY_REFUNDED', 'REFUNDED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_sales_branch_time` ON `sales` (`branch_id`, `sold_at`, `status`)');
    await queryRunner.query('CREATE INDEX `idx_sales_customer` ON `sales` (`customer_id`, `sold_at`)');
    await queryRunner.query('CREATE INDEX `idx_sales_shift` ON `sales` (`shift_id`, `sold_at`)');
    await queryRunner.query('CREATE TABLE `sale_lines` (\n  `id` CHAR(36) NOT NULL,\n  `sale_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `product_unit_id` CHAR(36) NOT NULL,\n  `quantity` DECIMAL(20,6) NOT NULL,\n  `conversion_factor` DECIMAL(20,6) NOT NULL,\n  `base_quantity` DECIMAL(20,6) NOT NULL,\n  `unit_price` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `discount_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `tax_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `line_total` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `lot_id` CHAR(36) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `ck_sale_lines_01` CHECK (quantity > 0),\n  CONSTRAINT `ck_sale_lines_02` CHECK (base_quantity > 0)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_sale_lines_sale` ON `sale_lines` (`sale_id`)');
    await queryRunner.query('CREATE INDEX `idx_sale_lines_product` ON `sale_lines` (`product_id`)');
    await queryRunner.query('CREATE TABLE `sale_line_allocations` (\n  `id` CHAR(36) NOT NULL,\n  `sale_line_id` CHAR(36) NOT NULL,\n  `lot_id` CHAR(36) NOT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `location_id` CHAR(36) NOT NULL,\n  `base_quantity` DECIMAL(20,6) NOT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_sale_line_allocations_01` UNIQUE (`sale_line_id`, `lot_id`, `warehouse_id`, `location_id`),\n  CONSTRAINT `ck_sale_line_allocations_01` CHECK (base_quantity > 0)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_alloc_sale_line` ON `sale_line_allocations` (`sale_line_id`)');
    await queryRunner.query('CREATE INDEX `idx_alloc_lot` ON `sale_line_allocations` (`lot_id`, `warehouse_id`)');
    await queryRunner.query("CREATE TABLE `sale_payments` (\n  `id` CHAR(36) NOT NULL,\n  `sale_id` CHAR(36) NOT NULL,\n  `payment_method` VARCHAR(32) NOT NULL,\n  `amount` DECIMAL(19,4) NOT NULL,\n  `provider` VARCHAR(128) NULL DEFAULT NULL,\n  `transaction_ref` VARCHAR(255) NULL DEFAULT NULL,\n  `paid_at` DATETIME(6) NOT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `ck_sale_payments_01` CHECK (amount > 0),\n  CONSTRAINT `ck_sale_payments_payment_method` CHECK (`payment_method` IN ('CASH', 'CARD', 'QR', 'BANK_TRANSFER', 'EWALLET', 'CUSTOMER_CREDIT'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_sale_payments_sale` ON `sale_payments` (`sale_id`)');
    await queryRunner.query('CREATE INDEX `idx_sale_payments_ref` ON `sale_payments` (`provider`, `transaction_ref`)');
    await queryRunner.query("CREATE TABLE `stock_transfers` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `transfer_number` VARCHAR(64) NOT NULL,\n  `from_branch_id` CHAR(36) NULL DEFAULT NULL,\n  `from_warehouse_id` CHAR(36) NOT NULL,\n  `to_branch_id` CHAR(36) NULL DEFAULT NULL,\n  `to_warehouse_id` CHAR(36) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',\n  `shipped_at` DATETIME(6) NULL DEFAULT NULL,\n  `received_at` DATETIME(6) NULL DEFAULT NULL,\n  `created_by` CHAR(36) NOT NULL,\n  `approved_by` CHAR(36) NULL DEFAULT NULL,\n  `received_by` CHAR(36) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_stock_transfers_01` UNIQUE (`organization_id`, `transfer_number`),\n  CONSTRAINT `ck_stock_transfers_01` CHECK (from_warehouse_id <> to_warehouse_id),\n  CONSTRAINT `ck_stock_transfers_status` CHECK (`status` IN ('DRAFT', 'APPROVED', 'SHIPPED', 'IN_TRANSIT', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_transfer_source` ON `stock_transfers` (`from_warehouse_id`, `status`, `shipped_at`)');
    await queryRunner.query('CREATE INDEX `idx_transfer_dest` ON `stock_transfers` (`to_warehouse_id`, `status`, `received_at`)');
    await queryRunner.query('CREATE TABLE `stock_transfer_lines` (\n  `id` CHAR(36) NOT NULL,\n  `transfer_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `lot_id` CHAR(36) NOT NULL,\n  `requested_qty` DECIMAL(20,6) NOT NULL DEFAULT 0,\n  `shipped_qty` DECIMAL(20,6) NOT NULL DEFAULT 0,\n  `received_qty` DECIMAL(20,6) NOT NULL DEFAULT 0,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `ck_stock_transfer_lines_01` CHECK (requested_qty >= 0),\n  CONSTRAINT `ck_stock_transfer_lines_02` CHECK (shipped_qty >= 0),\n  CONSTRAINT `ck_stock_transfer_lines_03` CHECK (received_qty >= 0),\n  CONSTRAINT `ck_stock_transfer_lines_04` CHECK (received_qty <= shipped_qty)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_transfer_lines_transfer` ON `stock_transfer_lines` (`transfer_id`)');
    await queryRunner.query('CREATE INDEX `idx_transfer_lines_product_lot` ON `stock_transfer_lines` (`product_id`, `lot_id`)');
    await queryRunner.query("CREATE TABLE `stock_counts` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NOT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `count_number` VARCHAR(64) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',\n  `started_at` DATETIME(6) NULL DEFAULT NULL,\n  `completed_at` DATETIME(6) NULL DEFAULT NULL,\n  `snapshot_sequence` BIGINT UNSIGNED NULL DEFAULT NULL,\n  `created_by` CHAR(36) NOT NULL,\n  `approved_by` CHAR(36) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_stock_counts_01` UNIQUE (`organization_id`, `count_number`),\n  CONSTRAINT `ck_stock_counts_status` CHECK (`status` IN ('DRAFT', 'IN_PROGRESS', 'COUNTED', 'APPROVED', 'POSTED', 'CANCELLED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_counts_wh_status` ON `stock_counts` (`warehouse_id`, `status`, `started_at`)');
    await queryRunner.query('CREATE TABLE `stock_count_lines` (\n  `id` CHAR(36) NOT NULL,\n  `stock_count_id` CHAR(36) NOT NULL,\n  `location_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `lot_id` CHAR(36) NOT NULL,\n  `expected_qty` DECIMAL(20,6) NOT NULL DEFAULT 0,\n  `counted_qty` DECIMAL(20,6) NOT NULL DEFAULT 0,\n  `difference_qty` DECIMAL(20,6) NOT NULL DEFAULT 0,\n  `counted_at` DATETIME(6) NOT NULL,\n  `counted_by` CHAR(36) NOT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_stock_count_lines_01` UNIQUE (`stock_count_id`, `location_id`, `product_id`, `lot_id`),\n  CONSTRAINT `ck_stock_count_lines_01` CHECK (counted_qty >= 0)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_count_lines_count` ON `stock_count_lines` (`stock_count_id`)');
    await queryRunner.query('CREATE INDEX `idx_count_lines_product` ON `stock_count_lines` (`product_id`, `lot_id`)');
    await queryRunner.query("CREATE TABLE `stock_adjustments` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NULL DEFAULT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `adjustment_number` VARCHAR(64) NOT NULL,\n  `reason_code` VARCHAR(32) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',\n  `adjusted_at` DATETIME(6) NULL DEFAULT NULL,\n  `created_by` CHAR(36) NOT NULL,\n  `approved_by` CHAR(36) NULL DEFAULT NULL,\n  `idempotency_key` VARCHAR(128) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_stock_adjustments_01` UNIQUE (`organization_id`, `adjustment_number`),\n  CONSTRAINT `uq_stock_adjustments_idempotency` UNIQUE (`organization_id`, `idempotency_key`),\n  CONSTRAINT `ck_stock_adjustments_status` CHECK (`status` IN ('DRAFT', 'APPROVED', 'POSTED', 'CANCELLED')),\n  CONSTRAINT `ck_stock_adjustments_reason_code` CHECK (`reason_code` IN ('DAMAGED', 'EXPIRED', 'LOST', 'FOUND', 'COUNT_DIFFERENCE', 'DATA_CORRECTION', 'SAMPLE', 'INTERNAL_USE', 'OTHER'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_adjustments_wh_status` ON `stock_adjustments` (`warehouse_id`, `status`, `adjusted_at`)');
    await queryRunner.query('CREATE TABLE `stock_adjustment_lines` (\n  `id` CHAR(36) NOT NULL,\n  `stock_adjustment_id` CHAR(36) NOT NULL,\n  `location_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `lot_id` CHAR(36) NOT NULL,\n  `quantity_delta` DECIMAL(20,6) NOT NULL,\n  `unit_cost` DECIMAL(19,4) NULL DEFAULT NULL,\n  `note` VARCHAR(1000) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `ck_stock_adjustment_lines_01` CHECK (quantity_delta <> 0)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_adjustment_lines_header` ON `stock_adjustment_lines` (`stock_adjustment_id`)');
    await queryRunner.query("CREATE TABLE `sales_returns` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NOT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `original_sale_id` CHAR(36) NULL DEFAULT NULL,\n  `return_number` VARCHAR(64) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',\n  `returned_at` DATETIME(6) NULL DEFAULT NULL,\n  `created_by` CHAR(36) NOT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_sales_returns_01` UNIQUE (`organization_id`, `return_number`),\n  CONSTRAINT `ck_sales_returns_status` CHECK (`status` IN ('DRAFT', 'APPROVED', 'POSTED', 'CANCELLED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_sales_returns_sale` ON `sales_returns` (`original_sale_id`)');
    await queryRunner.query('CREATE INDEX `idx_sales_returns_branch` ON `sales_returns` (`branch_id`, `returned_at`)');
    await queryRunner.query('CREATE TABLE `sales_return_lines` (\n  `id` CHAR(36) NOT NULL,\n  `sales_return_id` CHAR(36) NOT NULL,\n  `sale_line_id` CHAR(36) NULL DEFAULT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `lot_id` CHAR(36) NOT NULL,\n  `quantity` DECIMAL(20,6) NOT NULL,\n  `base_quantity` DECIMAL(20,6) NOT NULL,\n  `refund_amount` DECIMAL(19,4) NOT NULL DEFAULT 0,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `ck_sales_return_lines_01` CHECK (base_quantity > 0),\n  CONSTRAINT `ck_sales_return_lines_02` CHECK (refund_amount >= 0)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_sales_return_lines_header` ON `sales_return_lines` (`sales_return_id`)');
    await queryRunner.query('CREATE INDEX `idx_sales_return_lines_sale_line` ON `sales_return_lines` (`sale_line_id`)');
    await queryRunner.query("CREATE TABLE `supplier_returns` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NULL DEFAULT NULL,\n  `warehouse_id` CHAR(36) NOT NULL,\n  `supplier_id` CHAR(36) NOT NULL,\n  `return_number` VARCHAR(64) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',\n  `returned_at` DATETIME(6) NULL DEFAULT NULL,\n  `created_by` CHAR(36) NOT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_supplier_returns_01` UNIQUE (`organization_id`, `return_number`),\n  CONSTRAINT `ck_supplier_returns_status` CHECK (`status` IN ('DRAFT', 'APPROVED', 'POSTED', 'CANCELLED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_supplier_returns_supplier` ON `supplier_returns` (`supplier_id`, `returned_at`)');
    await queryRunner.query('CREATE INDEX `idx_supplier_returns_wh` ON `supplier_returns` (`warehouse_id`, `status`)');
    await queryRunner.query('CREATE TABLE `supplier_return_lines` (\n  `id` CHAR(36) NOT NULL,\n  `supplier_return_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `lot_id` CHAR(36) NOT NULL,\n  `quantity` DECIMAL(20,6) NOT NULL,\n  `base_quantity` DECIMAL(20,6) NOT NULL,\n  `unit_cost` DECIMAL(19,4) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `ck_supplier_return_lines_01` CHECK (base_quantity > 0)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_supplier_return_lines_header` ON `supplier_return_lines` (`supplier_return_id`)');
    await queryRunner.query('CREATE INDEX `idx_supplier_return_lines_product` ON `supplier_return_lines` (`product_id`, `lot_id`)');
    await queryRunner.query("CREATE TABLE `price_lists` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `code` VARCHAR(64) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_price_lists_01` UNIQUE (`organization_id`, `code`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE TABLE `price_list_items` (\n  `id` CHAR(36) NOT NULL,\n  `price_list_id` CHAR(36) NOT NULL,\n  `product_id` CHAR(36) NOT NULL,\n  `product_unit_id` CHAR(36) NOT NULL,\n  `price` DECIMAL(19,4) NOT NULL,\n  `effective_from` DATETIME(6) NOT NULL,\n  `effective_to` DATETIME(6) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `ck_price_list_items_01` CHECK (price >= 0),\n  CONSTRAINT `ck_price_list_items_02` CHECK (effective_to IS NULL OR effective_to > effective_from)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_price_lookup` ON `price_list_items` (`price_list_id`, `product_id`, `product_unit_id`, `effective_from`, `effective_to`)');
    await queryRunner.query("CREATE TABLE `promotions` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `code` VARCHAR(64) NOT NULL,\n  `name` VARCHAR(255) NOT NULL,\n  `promotion_type` VARCHAR(32) NOT NULL,\n  `start_at` DATETIME(6) NOT NULL,\n  `end_at` DATETIME(6) NOT NULL,\n  `status` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_promotions_01` UNIQUE (`organization_id`, `code`),\n  CONSTRAINT `ck_promotions_01` CHECK (end_at > start_at),\n  CONSTRAINT `ck_promotions_promotion_type` CHECK (`promotion_type` IN ('PERCENT', 'FIXED', 'BUY_X_GET_Y')),\n  CONSTRAINT `ck_promotions_status` CHECK (`status` IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'ENDED'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_promotions_active` ON `promotions` (`organization_id`, `status`, `start_at`, `end_at`)');
    await queryRunner.query('CREATE TABLE `audit_logs` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `actor_user_id` CHAR(36) NULL DEFAULT NULL,\n  `branch_id` CHAR(36) NULL DEFAULT NULL,\n  `action` VARCHAR(128) NOT NULL,\n  `entity_type` VARCHAR(128) NOT NULL,\n  `entity_id` CHAR(36) NOT NULL,\n  `before_data` JSON NULL DEFAULT NULL,\n  `after_data` JSON NULL DEFAULT NULL,\n  `ip_address` VARCHAR(45) NULL DEFAULT NULL,\n  `device_id` VARCHAR(128) NULL DEFAULT NULL,\n  `created_at` DATETIME(6) NOT NULL,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci');
    await queryRunner.query('CREATE INDEX `idx_audit_entity` ON `audit_logs` (`organization_id`, `entity_type`, `entity_id`, `created_at`)');
    await queryRunner.query('CREATE INDEX `idx_audit_actor` ON `audit_logs` (`actor_user_id`, `created_at`)');
    await queryRunner.query('CREATE INDEX `idx_audit_branch` ON `audit_logs` (`branch_id`, `created_at`)');
    await queryRunner.query("CREATE TABLE `document_sequences` (\n  `id` CHAR(36) NOT NULL,\n  `organization_id` CHAR(36) NOT NULL,\n  `branch_id` CHAR(36) NULL DEFAULT NULL,\n  `doc_type` VARCHAR(32) NOT NULL,\n  `prefix` VARCHAR(32) NOT NULL,\n  `period_key` VARCHAR(16) NOT NULL,\n  `current_no` BIGINT UNSIGNED NOT NULL DEFAULT 0,\n  `version` BIGINT UNSIGNED NOT NULL DEFAULT 0,\n  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\n  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\n  `branch_scope_key` CHAR(36) GENERATED ALWAYS AS (coalesce(`branch_id`, '00000000-0000-0000-0000-000000000000')) STORED,\n  PRIMARY KEY (`id`),\n  CONSTRAINT `uq_document_sequences_01` UNIQUE (`organization_id`, `branch_scope_key`, `doc_type`, `period_key`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
    await queryRunner.query('CREATE INDEX `idx_docseq_lookup` ON `document_sequences` (`organization_id`, `branch_id`, `doc_type`, `period_key`)');
    await queryRunner.query('ALTER TABLE `branches` ADD CONSTRAINT `fk_branches_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `warehouses` ADD CONSTRAINT `fk_warehouses_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `warehouses` ADD CONSTRAINT `fk_warehouses_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_locations` ADD CONSTRAINT `fk_stock_locations_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `users` ADD CONSTRAINT `fk_users_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `roles` ADD CONSTRAINT `fk_roles_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `user_roles` ADD CONSTRAINT `fk_user_roles_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE');
    await queryRunner.query('ALTER TABLE `user_roles` ADD CONSTRAINT `fk_user_roles_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE');
    await queryRunner.query('ALTER TABLE `role_permissions` ADD CONSTRAINT `fk_role_permissions_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE');
    await queryRunner.query('ALTER TABLE `role_permissions` ADD CONSTRAINT `fk_role_permissions_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE');
    await queryRunner.query('ALTER TABLE `user_branch_access` ADD CONSTRAINT `fk_user_branch_access_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE');
    await queryRunner.query('ALTER TABLE `user_branch_access` ADD CONSTRAINT `fk_user_branch_access_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE CASCADE');
    await queryRunner.query('ALTER TABLE `categories` ADD CONSTRAINT `fk_categories_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `categories` ADD CONSTRAINT `fk_categories_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `manufacturers` ADD CONSTRAINT `fk_manufacturers_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `products` ADD CONSTRAINT `fk_products_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `products` ADD CONSTRAINT `fk_products_category_id` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `products` ADD CONSTRAINT `fk_products_manufacturer_id` FOREIGN KEY (`manufacturer_id`) REFERENCES `manufacturers` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `products` ADD CONSTRAINT `fk_products_base_unit_id` FOREIGN KEY (`base_unit_id`) REFERENCES `units` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `product_units` ADD CONSTRAINT `fk_product_units_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `product_units` ADD CONSTRAINT `fk_product_units_unit_id` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `product_barcodes` ADD CONSTRAINT `fk_product_barcodes_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `product_barcodes` ADD CONSTRAINT `fk_product_barcodes_product_unit_id` FOREIGN KEY (`product_unit_id`) REFERENCES `product_units` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `suppliers` ADD CONSTRAINT `fk_suppliers_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `customers` ADD CONSTRAINT `fk_customers_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_lots` ADD CONSTRAINT `fk_inventory_lots_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_lots` ADD CONSTRAINT `fk_inventory_lots_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_lots` ADD CONSTRAINT `fk_inventory_lots_manufacturer_id` FOREIGN KEY (`manufacturer_id`) REFERENCES `manufacturers` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_movements` ADD CONSTRAINT `fk_inventory_movements_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_movements` ADD CONSTRAINT `fk_inventory_movements_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_movements` ADD CONSTRAINT `fk_inventory_movements_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_movements` ADD CONSTRAINT `fk_inventory_movements_location_id` FOREIGN KEY (`location_id`) REFERENCES `stock_locations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_movements` ADD CONSTRAINT `fk_inventory_movements_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_movements` ADD CONSTRAINT `fk_inventory_movements_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_movements` ADD CONSTRAINT `fk_inventory_movements_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_movements` ADD CONSTRAINT `fk_inventory_movements_device_id` FOREIGN KEY (`device_id`) REFERENCES `pos_devices` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_movements` ADD CONSTRAINT `fk_inventory_movements_reversal_of_id` FOREIGN KEY (`reversal_of_id`) REFERENCES `inventory_movements` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_balances` ADD CONSTRAINT `fk_inventory_balances_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_balances` ADD CONSTRAINT `fk_inventory_balances_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_balances` ADD CONSTRAINT `fk_inventory_balances_location_id` FOREIGN KEY (`location_id`) REFERENCES `stock_locations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_balances` ADD CONSTRAINT `fk_inventory_balances_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_balances` ADD CONSTRAINT `fk_inventory_balances_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_reservations` ADD CONSTRAINT `fk_inventory_reservations_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_reservations` ADD CONSTRAINT `fk_inventory_reservations_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_reservations` ADD CONSTRAINT `fk_inventory_reservations_location_id` FOREIGN KEY (`location_id`) REFERENCES `stock_locations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_reservations` ADD CONSTRAINT `fk_inventory_reservations_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `inventory_reservations` ADD CONSTRAINT `fk_inventory_reservations_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `purchase_orders` ADD CONSTRAINT `fk_purchase_orders_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `purchase_orders` ADD CONSTRAINT `fk_purchase_orders_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `purchase_orders` ADD CONSTRAINT `fk_purchase_orders_supplier_id` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `purchase_orders` ADD CONSTRAINT `fk_purchase_orders_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `purchase_order_lines` ADD CONSTRAINT `fk_purchase_order_lines_purchase_order_id` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `purchase_order_lines` ADD CONSTRAINT `fk_purchase_order_lines_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `purchase_order_lines` ADD CONSTRAINT `fk_purchase_order_lines_product_unit_id` FOREIGN KEY (`product_unit_id`) REFERENCES `product_units` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `goods_receipts` ADD CONSTRAINT `fk_goods_receipts_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `goods_receipts` ADD CONSTRAINT `fk_goods_receipts_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `goods_receipts` ADD CONSTRAINT `fk_goods_receipts_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `goods_receipts` ADD CONSTRAINT `fk_goods_receipts_supplier_id` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `goods_receipts` ADD CONSTRAINT `fk_goods_receipts_purchase_order_id` FOREIGN KEY (`purchase_order_id`) REFERENCES `purchase_orders` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `goods_receipts` ADD CONSTRAINT `fk_goods_receipts_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `goods_receipt_lines` ADD CONSTRAINT `fk_goods_receipt_lines_goods_receipt_id` FOREIGN KEY (`goods_receipt_id`) REFERENCES `goods_receipts` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `goods_receipt_lines` ADD CONSTRAINT `fk_goods_receipt_lines_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `goods_receipt_lines` ADD CONSTRAINT `fk_goods_receipt_lines_product_unit_id` FOREIGN KEY (`product_unit_id`) REFERENCES `product_units` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `goods_receipt_lines` ADD CONSTRAINT `fk_goods_receipt_lines_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `pos_devices` ADD CONSTRAINT `fk_pos_devices_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `pos_shifts` ADD CONSTRAINT `fk_pos_shifts_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `pos_shifts` ADD CONSTRAINT `fk_pos_shifts_pos_device_id` FOREIGN KEY (`pos_device_id`) REFERENCES `pos_devices` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `pos_shifts` ADD CONSTRAINT `fk_pos_shifts_opened_by` FOREIGN KEY (`opened_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales` ADD CONSTRAINT `fk_sales_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales` ADD CONSTRAINT `fk_sales_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales` ADD CONSTRAINT `fk_sales_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales` ADD CONSTRAINT `fk_sales_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales` ADD CONSTRAINT `fk_sales_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales` ADD CONSTRAINT `fk_sales_pos_device_id` FOREIGN KEY (`pos_device_id`) REFERENCES `pos_devices` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales` ADD CONSTRAINT `fk_sales_shift_id` FOREIGN KEY (`shift_id`) REFERENCES `pos_shifts` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sale_lines` ADD CONSTRAINT `fk_sale_lines_sale_id` FOREIGN KEY (`sale_id`) REFERENCES `sales` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sale_lines` ADD CONSTRAINT `fk_sale_lines_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sale_lines` ADD CONSTRAINT `fk_sale_lines_product_unit_id` FOREIGN KEY (`product_unit_id`) REFERENCES `product_units` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sale_lines` ADD CONSTRAINT `fk_sale_lines_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sale_line_allocations` ADD CONSTRAINT `fk_sale_line_allocations_sale_line_id` FOREIGN KEY (`sale_line_id`) REFERENCES `sale_lines` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sale_line_allocations` ADD CONSTRAINT `fk_sale_line_allocations_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sale_line_allocations` ADD CONSTRAINT `fk_sale_line_allocations_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sale_line_allocations` ADD CONSTRAINT `fk_sale_line_allocations_location_id` FOREIGN KEY (`location_id`) REFERENCES `stock_locations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sale_payments` ADD CONSTRAINT `fk_sale_payments_sale_id` FOREIGN KEY (`sale_id`) REFERENCES `sales` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfers` ADD CONSTRAINT `fk_stock_transfers_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfers` ADD CONSTRAINT `fk_stock_transfers_from_branch_id` FOREIGN KEY (`from_branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfers` ADD CONSTRAINT `fk_stock_transfers_from_warehouse_id` FOREIGN KEY (`from_warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfers` ADD CONSTRAINT `fk_stock_transfers_to_branch_id` FOREIGN KEY (`to_branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfers` ADD CONSTRAINT `fk_stock_transfers_to_warehouse_id` FOREIGN KEY (`to_warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfers` ADD CONSTRAINT `fk_stock_transfers_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfers` ADD CONSTRAINT `fk_stock_transfers_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfers` ADD CONSTRAINT `fk_stock_transfers_received_by` FOREIGN KEY (`received_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfer_lines` ADD CONSTRAINT `fk_stock_transfer_lines_transfer_id` FOREIGN KEY (`transfer_id`) REFERENCES `stock_transfers` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfer_lines` ADD CONSTRAINT `fk_stock_transfer_lines_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_transfer_lines` ADD CONSTRAINT `fk_stock_transfer_lines_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_counts` ADD CONSTRAINT `fk_stock_counts_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_counts` ADD CONSTRAINT `fk_stock_counts_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_counts` ADD CONSTRAINT `fk_stock_counts_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_counts` ADD CONSTRAINT `fk_stock_counts_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_counts` ADD CONSTRAINT `fk_stock_counts_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_count_lines` ADD CONSTRAINT `fk_stock_count_lines_stock_count_id` FOREIGN KEY (`stock_count_id`) REFERENCES `stock_counts` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_count_lines` ADD CONSTRAINT `fk_stock_count_lines_location_id` FOREIGN KEY (`location_id`) REFERENCES `stock_locations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_count_lines` ADD CONSTRAINT `fk_stock_count_lines_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_count_lines` ADD CONSTRAINT `fk_stock_count_lines_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_count_lines` ADD CONSTRAINT `fk_stock_count_lines_counted_by` FOREIGN KEY (`counted_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_adjustments` ADD CONSTRAINT `fk_stock_adjustments_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_adjustments` ADD CONSTRAINT `fk_stock_adjustments_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_adjustments` ADD CONSTRAINT `fk_stock_adjustments_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_adjustments` ADD CONSTRAINT `fk_stock_adjustments_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_adjustments` ADD CONSTRAINT `fk_stock_adjustments_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_adjustment_lines` ADD CONSTRAINT `fk_stock_adjustment_lines_stock_adjustment_id` FOREIGN KEY (`stock_adjustment_id`) REFERENCES `stock_adjustments` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_adjustment_lines` ADD CONSTRAINT `fk_stock_adjustment_lines_location_id` FOREIGN KEY (`location_id`) REFERENCES `stock_locations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_adjustment_lines` ADD CONSTRAINT `fk_stock_adjustment_lines_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_adjustment_lines` ADD CONSTRAINT `fk_stock_adjustment_lines_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales_returns` ADD CONSTRAINT `fk_sales_returns_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales_returns` ADD CONSTRAINT `fk_sales_returns_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales_returns` ADD CONSTRAINT `fk_sales_returns_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales_returns` ADD CONSTRAINT `fk_sales_returns_original_sale_id` FOREIGN KEY (`original_sale_id`) REFERENCES `sales` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales_returns` ADD CONSTRAINT `fk_sales_returns_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales_return_lines` ADD CONSTRAINT `fk_sales_return_lines_sales_return_id` FOREIGN KEY (`sales_return_id`) REFERENCES `sales_returns` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales_return_lines` ADD CONSTRAINT `fk_sales_return_lines_sale_line_id` FOREIGN KEY (`sale_line_id`) REFERENCES `sale_lines` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales_return_lines` ADD CONSTRAINT `fk_sales_return_lines_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `sales_return_lines` ADD CONSTRAINT `fk_sales_return_lines_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `supplier_returns` ADD CONSTRAINT `fk_supplier_returns_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `supplier_returns` ADD CONSTRAINT `fk_supplier_returns_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `supplier_returns` ADD CONSTRAINT `fk_supplier_returns_warehouse_id` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `supplier_returns` ADD CONSTRAINT `fk_supplier_returns_supplier_id` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `supplier_returns` ADD CONSTRAINT `fk_supplier_returns_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `supplier_return_lines` ADD CONSTRAINT `fk_supplier_return_lines_supplier_return_id` FOREIGN KEY (`supplier_return_id`) REFERENCES `supplier_returns` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `supplier_return_lines` ADD CONSTRAINT `fk_supplier_return_lines_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `supplier_return_lines` ADD CONSTRAINT `fk_supplier_return_lines_lot_id` FOREIGN KEY (`lot_id`) REFERENCES `inventory_lots` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `price_lists` ADD CONSTRAINT `fk_price_lists_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `price_list_items` ADD CONSTRAINT `fk_price_list_items_price_list_id` FOREIGN KEY (`price_list_id`) REFERENCES `price_lists` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `price_list_items` ADD CONSTRAINT `fk_price_list_items_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `price_list_items` ADD CONSTRAINT `fk_price_list_items_product_unit_id` FOREIGN KEY (`product_unit_id`) REFERENCES `product_units` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `promotions` ADD CONSTRAINT `fk_promotions_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `audit_logs` ADD CONSTRAINT `fk_audit_logs_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `audit_logs` ADD CONSTRAINT `fk_audit_logs_actor_user_id` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `audit_logs` ADD CONSTRAINT `fk_audit_logs_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `document_sequences` ADD CONSTRAINT `fk_document_sequences_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `document_sequences` ADD CONSTRAINT `fk_document_sequences_branch_id` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE RESTRICT');
    await queryRunner.query('ALTER TABLE `stock_counts` ADD CONSTRAINT `fk_stock_counts_snapshot_sequence` FOREIGN KEY (`snapshot_sequence`) REFERENCES `inventory_movements` (`ledger_seq`) ON DELETE RESTRICT');
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE `document_sequences` DROP FOREIGN KEY `fk_document_sequences_branch_id`');
    await queryRunner.query('ALTER TABLE `document_sequences` DROP FOREIGN KEY `fk_document_sequences_organization_id`');
    await queryRunner.query('ALTER TABLE `audit_logs` DROP FOREIGN KEY `fk_audit_logs_branch_id`');
    await queryRunner.query('ALTER TABLE `audit_logs` DROP FOREIGN KEY `fk_audit_logs_actor_user_id`');
    await queryRunner.query('ALTER TABLE `audit_logs` DROP FOREIGN KEY `fk_audit_logs_organization_id`');
    await queryRunner.query('ALTER TABLE `promotions` DROP FOREIGN KEY `fk_promotions_organization_id`');
    await queryRunner.query('ALTER TABLE `price_list_items` DROP FOREIGN KEY `fk_price_list_items_product_unit_id`');
    await queryRunner.query('ALTER TABLE `price_list_items` DROP FOREIGN KEY `fk_price_list_items_product_id`');
    await queryRunner.query('ALTER TABLE `price_list_items` DROP FOREIGN KEY `fk_price_list_items_price_list_id`');
    await queryRunner.query('ALTER TABLE `price_lists` DROP FOREIGN KEY `fk_price_lists_organization_id`');
    await queryRunner.query('ALTER TABLE `supplier_return_lines` DROP FOREIGN KEY `fk_supplier_return_lines_lot_id`');
    await queryRunner.query('ALTER TABLE `supplier_return_lines` DROP FOREIGN KEY `fk_supplier_return_lines_product_id`');
    await queryRunner.query('ALTER TABLE `supplier_return_lines` DROP FOREIGN KEY `fk_supplier_return_lines_supplier_return_id`');
    await queryRunner.query('ALTER TABLE `supplier_returns` DROP FOREIGN KEY `fk_supplier_returns_created_by`');
    await queryRunner.query('ALTER TABLE `supplier_returns` DROP FOREIGN KEY `fk_supplier_returns_supplier_id`');
    await queryRunner.query('ALTER TABLE `supplier_returns` DROP FOREIGN KEY `fk_supplier_returns_warehouse_id`');
    await queryRunner.query('ALTER TABLE `supplier_returns` DROP FOREIGN KEY `fk_supplier_returns_branch_id`');
    await queryRunner.query('ALTER TABLE `supplier_returns` DROP FOREIGN KEY `fk_supplier_returns_organization_id`');
    await queryRunner.query('ALTER TABLE `sales_return_lines` DROP FOREIGN KEY `fk_sales_return_lines_lot_id`');
    await queryRunner.query('ALTER TABLE `sales_return_lines` DROP FOREIGN KEY `fk_sales_return_lines_product_id`');
    await queryRunner.query('ALTER TABLE `sales_return_lines` DROP FOREIGN KEY `fk_sales_return_lines_sale_line_id`');
    await queryRunner.query('ALTER TABLE `sales_return_lines` DROP FOREIGN KEY `fk_sales_return_lines_sales_return_id`');
    await queryRunner.query('ALTER TABLE `sales_returns` DROP FOREIGN KEY `fk_sales_returns_created_by`');
    await queryRunner.query('ALTER TABLE `sales_returns` DROP FOREIGN KEY `fk_sales_returns_original_sale_id`');
    await queryRunner.query('ALTER TABLE `sales_returns` DROP FOREIGN KEY `fk_sales_returns_warehouse_id`');
    await queryRunner.query('ALTER TABLE `sales_returns` DROP FOREIGN KEY `fk_sales_returns_branch_id`');
    await queryRunner.query('ALTER TABLE `sales_returns` DROP FOREIGN KEY `fk_sales_returns_organization_id`');
    await queryRunner.query('ALTER TABLE `stock_adjustment_lines` DROP FOREIGN KEY `fk_stock_adjustment_lines_lot_id`');
    await queryRunner.query('ALTER TABLE `stock_adjustment_lines` DROP FOREIGN KEY `fk_stock_adjustment_lines_product_id`');
    await queryRunner.query('ALTER TABLE `stock_adjustment_lines` DROP FOREIGN KEY `fk_stock_adjustment_lines_location_id`');
    await queryRunner.query('ALTER TABLE `stock_adjustment_lines` DROP FOREIGN KEY `fk_stock_adjustment_lines_stock_adjustment_id`');
    await queryRunner.query('ALTER TABLE `stock_adjustments` DROP FOREIGN KEY `fk_stock_adjustments_approved_by`');
    await queryRunner.query('ALTER TABLE `stock_adjustments` DROP FOREIGN KEY `fk_stock_adjustments_created_by`');
    await queryRunner.query('ALTER TABLE `stock_adjustments` DROP FOREIGN KEY `fk_stock_adjustments_warehouse_id`');
    await queryRunner.query('ALTER TABLE `stock_adjustments` DROP FOREIGN KEY `fk_stock_adjustments_branch_id`');
    await queryRunner.query('ALTER TABLE `stock_adjustments` DROP FOREIGN KEY `fk_stock_adjustments_organization_id`');
    await queryRunner.query('ALTER TABLE `stock_count_lines` DROP FOREIGN KEY `fk_stock_count_lines_counted_by`');
    await queryRunner.query('ALTER TABLE `stock_count_lines` DROP FOREIGN KEY `fk_stock_count_lines_lot_id`');
    await queryRunner.query('ALTER TABLE `stock_count_lines` DROP FOREIGN KEY `fk_stock_count_lines_product_id`');
    await queryRunner.query('ALTER TABLE `stock_count_lines` DROP FOREIGN KEY `fk_stock_count_lines_location_id`');
    await queryRunner.query('ALTER TABLE `stock_count_lines` DROP FOREIGN KEY `fk_stock_count_lines_stock_count_id`');
    await queryRunner.query('ALTER TABLE `stock_counts` DROP FOREIGN KEY `fk_stock_counts_approved_by`');
    await queryRunner.query('ALTER TABLE `stock_counts` DROP FOREIGN KEY `fk_stock_counts_created_by`');
    await queryRunner.query('ALTER TABLE `stock_counts` DROP FOREIGN KEY `fk_stock_counts_warehouse_id`');
    await queryRunner.query('ALTER TABLE `stock_counts` DROP FOREIGN KEY `fk_stock_counts_branch_id`');
    await queryRunner.query('ALTER TABLE `stock_counts` DROP FOREIGN KEY `fk_stock_counts_organization_id`');
    await queryRunner.query('ALTER TABLE `stock_transfer_lines` DROP FOREIGN KEY `fk_stock_transfer_lines_lot_id`');
    await queryRunner.query('ALTER TABLE `stock_transfer_lines` DROP FOREIGN KEY `fk_stock_transfer_lines_product_id`');
    await queryRunner.query('ALTER TABLE `stock_transfer_lines` DROP FOREIGN KEY `fk_stock_transfer_lines_transfer_id`');
    await queryRunner.query('ALTER TABLE `stock_transfers` DROP FOREIGN KEY `fk_stock_transfers_received_by`');
    await queryRunner.query('ALTER TABLE `stock_transfers` DROP FOREIGN KEY `fk_stock_transfers_approved_by`');
    await queryRunner.query('ALTER TABLE `stock_transfers` DROP FOREIGN KEY `fk_stock_transfers_created_by`');
    await queryRunner.query('ALTER TABLE `stock_transfers` DROP FOREIGN KEY `fk_stock_transfers_to_warehouse_id`');
    await queryRunner.query('ALTER TABLE `stock_transfers` DROP FOREIGN KEY `fk_stock_transfers_to_branch_id`');
    await queryRunner.query('ALTER TABLE `stock_transfers` DROP FOREIGN KEY `fk_stock_transfers_from_warehouse_id`');
    await queryRunner.query('ALTER TABLE `stock_transfers` DROP FOREIGN KEY `fk_stock_transfers_from_branch_id`');
    await queryRunner.query('ALTER TABLE `stock_transfers` DROP FOREIGN KEY `fk_stock_transfers_organization_id`');
    await queryRunner.query('ALTER TABLE `sale_payments` DROP FOREIGN KEY `fk_sale_payments_sale_id`');
    await queryRunner.query('ALTER TABLE `sale_line_allocations` DROP FOREIGN KEY `fk_sale_line_allocations_location_id`');
    await queryRunner.query('ALTER TABLE `sale_line_allocations` DROP FOREIGN KEY `fk_sale_line_allocations_warehouse_id`');
    await queryRunner.query('ALTER TABLE `sale_line_allocations` DROP FOREIGN KEY `fk_sale_line_allocations_lot_id`');
    await queryRunner.query('ALTER TABLE `sale_line_allocations` DROP FOREIGN KEY `fk_sale_line_allocations_sale_line_id`');
    await queryRunner.query('ALTER TABLE `sale_lines` DROP FOREIGN KEY `fk_sale_lines_lot_id`');
    await queryRunner.query('ALTER TABLE `sale_lines` DROP FOREIGN KEY `fk_sale_lines_product_unit_id`');
    await queryRunner.query('ALTER TABLE `sale_lines` DROP FOREIGN KEY `fk_sale_lines_product_id`');
    await queryRunner.query('ALTER TABLE `sale_lines` DROP FOREIGN KEY `fk_sale_lines_sale_id`');
    await queryRunner.query('ALTER TABLE `sales` DROP FOREIGN KEY `fk_sales_shift_id`');
    await queryRunner.query('ALTER TABLE `sales` DROP FOREIGN KEY `fk_sales_pos_device_id`');
    await queryRunner.query('ALTER TABLE `sales` DROP FOREIGN KEY `fk_sales_created_by`');
    await queryRunner.query('ALTER TABLE `sales` DROP FOREIGN KEY `fk_sales_customer_id`');
    await queryRunner.query('ALTER TABLE `sales` DROP FOREIGN KEY `fk_sales_warehouse_id`');
    await queryRunner.query('ALTER TABLE `sales` DROP FOREIGN KEY `fk_sales_branch_id`');
    await queryRunner.query('ALTER TABLE `sales` DROP FOREIGN KEY `fk_sales_organization_id`');
    await queryRunner.query('ALTER TABLE `pos_shifts` DROP FOREIGN KEY `fk_pos_shifts_opened_by`');
    await queryRunner.query('ALTER TABLE `pos_shifts` DROP FOREIGN KEY `fk_pos_shifts_pos_device_id`');
    await queryRunner.query('ALTER TABLE `pos_shifts` DROP FOREIGN KEY `fk_pos_shifts_branch_id`');
    await queryRunner.query('ALTER TABLE `pos_devices` DROP FOREIGN KEY `fk_pos_devices_branch_id`');
    await queryRunner.query('ALTER TABLE `goods_receipt_lines` DROP FOREIGN KEY `fk_goods_receipt_lines_lot_id`');
    await queryRunner.query('ALTER TABLE `goods_receipt_lines` DROP FOREIGN KEY `fk_goods_receipt_lines_product_unit_id`');
    await queryRunner.query('ALTER TABLE `goods_receipt_lines` DROP FOREIGN KEY `fk_goods_receipt_lines_product_id`');
    await queryRunner.query('ALTER TABLE `goods_receipt_lines` DROP FOREIGN KEY `fk_goods_receipt_lines_goods_receipt_id`');
    await queryRunner.query('ALTER TABLE `goods_receipts` DROP FOREIGN KEY `fk_goods_receipts_created_by`');
    await queryRunner.query('ALTER TABLE `goods_receipts` DROP FOREIGN KEY `fk_goods_receipts_purchase_order_id`');
    await queryRunner.query('ALTER TABLE `goods_receipts` DROP FOREIGN KEY `fk_goods_receipts_supplier_id`');
    await queryRunner.query('ALTER TABLE `goods_receipts` DROP FOREIGN KEY `fk_goods_receipts_warehouse_id`');
    await queryRunner.query('ALTER TABLE `goods_receipts` DROP FOREIGN KEY `fk_goods_receipts_branch_id`');
    await queryRunner.query('ALTER TABLE `goods_receipts` DROP FOREIGN KEY `fk_goods_receipts_organization_id`');
    await queryRunner.query('ALTER TABLE `purchase_order_lines` DROP FOREIGN KEY `fk_purchase_order_lines_product_unit_id`');
    await queryRunner.query('ALTER TABLE `purchase_order_lines` DROP FOREIGN KEY `fk_purchase_order_lines_product_id`');
    await queryRunner.query('ALTER TABLE `purchase_order_lines` DROP FOREIGN KEY `fk_purchase_order_lines_purchase_order_id`');
    await queryRunner.query('ALTER TABLE `purchase_orders` DROP FOREIGN KEY `fk_purchase_orders_created_by`');
    await queryRunner.query('ALTER TABLE `purchase_orders` DROP FOREIGN KEY `fk_purchase_orders_supplier_id`');
    await queryRunner.query('ALTER TABLE `purchase_orders` DROP FOREIGN KEY `fk_purchase_orders_branch_id`');
    await queryRunner.query('ALTER TABLE `purchase_orders` DROP FOREIGN KEY `fk_purchase_orders_organization_id`');
    await queryRunner.query('ALTER TABLE `inventory_reservations` DROP FOREIGN KEY `fk_inventory_reservations_lot_id`');
    await queryRunner.query('ALTER TABLE `inventory_reservations` DROP FOREIGN KEY `fk_inventory_reservations_product_id`');
    await queryRunner.query('ALTER TABLE `inventory_reservations` DROP FOREIGN KEY `fk_inventory_reservations_location_id`');
    await queryRunner.query('ALTER TABLE `inventory_reservations` DROP FOREIGN KEY `fk_inventory_reservations_warehouse_id`');
    await queryRunner.query('ALTER TABLE `inventory_reservations` DROP FOREIGN KEY `fk_inventory_reservations_organization_id`');
    await queryRunner.query('ALTER TABLE `inventory_balances` DROP FOREIGN KEY `fk_inventory_balances_lot_id`');
    await queryRunner.query('ALTER TABLE `inventory_balances` DROP FOREIGN KEY `fk_inventory_balances_product_id`');
    await queryRunner.query('ALTER TABLE `inventory_balances` DROP FOREIGN KEY `fk_inventory_balances_location_id`');
    await queryRunner.query('ALTER TABLE `inventory_balances` DROP FOREIGN KEY `fk_inventory_balances_warehouse_id`');
    await queryRunner.query('ALTER TABLE `inventory_balances` DROP FOREIGN KEY `fk_inventory_balances_organization_id`');
    await queryRunner.query('ALTER TABLE `inventory_movements` DROP FOREIGN KEY `fk_inventory_movements_reversal_of_id`');
    await queryRunner.query('ALTER TABLE `inventory_movements` DROP FOREIGN KEY `fk_inventory_movements_device_id`');
    await queryRunner.query('ALTER TABLE `inventory_movements` DROP FOREIGN KEY `fk_inventory_movements_created_by`');
    await queryRunner.query('ALTER TABLE `inventory_movements` DROP FOREIGN KEY `fk_inventory_movements_lot_id`');
    await queryRunner.query('ALTER TABLE `inventory_movements` DROP FOREIGN KEY `fk_inventory_movements_product_id`');
    await queryRunner.query('ALTER TABLE `inventory_movements` DROP FOREIGN KEY `fk_inventory_movements_location_id`');
    await queryRunner.query('ALTER TABLE `inventory_movements` DROP FOREIGN KEY `fk_inventory_movements_warehouse_id`');
    await queryRunner.query('ALTER TABLE `inventory_movements` DROP FOREIGN KEY `fk_inventory_movements_branch_id`');
    await queryRunner.query('ALTER TABLE `inventory_movements` DROP FOREIGN KEY `fk_inventory_movements_organization_id`');
    await queryRunner.query('ALTER TABLE `inventory_lots` DROP FOREIGN KEY `fk_inventory_lots_manufacturer_id`');
    await queryRunner.query('ALTER TABLE `inventory_lots` DROP FOREIGN KEY `fk_inventory_lots_product_id`');
    await queryRunner.query('ALTER TABLE `inventory_lots` DROP FOREIGN KEY `fk_inventory_lots_organization_id`');
    await queryRunner.query('ALTER TABLE `customers` DROP FOREIGN KEY `fk_customers_organization_id`');
    await queryRunner.query('ALTER TABLE `suppliers` DROP FOREIGN KEY `fk_suppliers_organization_id`');
    await queryRunner.query('ALTER TABLE `product_barcodes` DROP FOREIGN KEY `fk_product_barcodes_product_unit_id`');
    await queryRunner.query('ALTER TABLE `product_barcodes` DROP FOREIGN KEY `fk_product_barcodes_product_id`');
    await queryRunner.query('ALTER TABLE `product_units` DROP FOREIGN KEY `fk_product_units_unit_id`');
    await queryRunner.query('ALTER TABLE `product_units` DROP FOREIGN KEY `fk_product_units_product_id`');
    await queryRunner.query('ALTER TABLE `products` DROP FOREIGN KEY `fk_products_base_unit_id`');
    await queryRunner.query('ALTER TABLE `products` DROP FOREIGN KEY `fk_products_manufacturer_id`');
    await queryRunner.query('ALTER TABLE `products` DROP FOREIGN KEY `fk_products_category_id`');
    await queryRunner.query('ALTER TABLE `products` DROP FOREIGN KEY `fk_products_organization_id`');
    await queryRunner.query('ALTER TABLE `manufacturers` DROP FOREIGN KEY `fk_manufacturers_organization_id`');
    await queryRunner.query('ALTER TABLE `categories` DROP FOREIGN KEY `fk_categories_parent_id`');
    await queryRunner.query('ALTER TABLE `categories` DROP FOREIGN KEY `fk_categories_organization_id`');
    await queryRunner.query('ALTER TABLE `user_branch_access` DROP FOREIGN KEY `fk_user_branch_access_branch_id`');
    await queryRunner.query('ALTER TABLE `user_branch_access` DROP FOREIGN KEY `fk_user_branch_access_user_id`');
    await queryRunner.query('ALTER TABLE `role_permissions` DROP FOREIGN KEY `fk_role_permissions_permission_id`');
    await queryRunner.query('ALTER TABLE `role_permissions` DROP FOREIGN KEY `fk_role_permissions_role_id`');
    await queryRunner.query('ALTER TABLE `user_roles` DROP FOREIGN KEY `fk_user_roles_role_id`');
    await queryRunner.query('ALTER TABLE `user_roles` DROP FOREIGN KEY `fk_user_roles_user_id`');
    await queryRunner.query('ALTER TABLE `roles` DROP FOREIGN KEY `fk_roles_organization_id`');
    await queryRunner.query('ALTER TABLE `users` DROP FOREIGN KEY `fk_users_organization_id`');
    await queryRunner.query('ALTER TABLE `stock_locations` DROP FOREIGN KEY `fk_stock_locations_warehouse_id`');
    await queryRunner.query('ALTER TABLE `warehouses` DROP FOREIGN KEY `fk_warehouses_branch_id`');
    await queryRunner.query('ALTER TABLE `warehouses` DROP FOREIGN KEY `fk_warehouses_organization_id`');
    await queryRunner.query('ALTER TABLE `branches` DROP FOREIGN KEY `fk_branches_organization_id`');
    await queryRunner.query('ALTER TABLE `stock_counts` DROP FOREIGN KEY `fk_stock_counts_snapshot_sequence`');
    await queryRunner.query('DROP TABLE `document_sequences`');
    await queryRunner.query('DROP TABLE `audit_logs`');
    await queryRunner.query('DROP TABLE `promotions`');
    await queryRunner.query('DROP TABLE `price_list_items`');
    await queryRunner.query('DROP TABLE `price_lists`');
    await queryRunner.query('DROP TABLE `supplier_return_lines`');
    await queryRunner.query('DROP TABLE `supplier_returns`');
    await queryRunner.query('DROP TABLE `sales_return_lines`');
    await queryRunner.query('DROP TABLE `sales_returns`');
    await queryRunner.query('DROP TABLE `stock_adjustment_lines`');
    await queryRunner.query('DROP TABLE `stock_adjustments`');
    await queryRunner.query('DROP TABLE `stock_count_lines`');
    await queryRunner.query('DROP TABLE `stock_counts`');
    await queryRunner.query('DROP TABLE `stock_transfer_lines`');
    await queryRunner.query('DROP TABLE `stock_transfers`');
    await queryRunner.query('DROP TABLE `sale_payments`');
    await queryRunner.query('DROP TABLE `sale_line_allocations`');
    await queryRunner.query('DROP TABLE `sale_lines`');
    await queryRunner.query('DROP TABLE `sales`');
    await queryRunner.query('DROP TABLE `pos_shifts`');
    await queryRunner.query('DROP TABLE `pos_devices`');
    await queryRunner.query('DROP TABLE `goods_receipt_lines`');
    await queryRunner.query('DROP TABLE `goods_receipts`');
    await queryRunner.query('DROP TABLE `purchase_order_lines`');
    await queryRunner.query('DROP TABLE `purchase_orders`');
    await queryRunner.query('DROP TABLE `inventory_reservations`');
    await queryRunner.query('DROP TABLE `inventory_balances`');
    await queryRunner.query('DROP TABLE `inventory_movements`');
    await queryRunner.query('DROP TABLE `inventory_lots`');
    await queryRunner.query('DROP TABLE `customers`');
    await queryRunner.query('DROP TABLE `suppliers`');
    await queryRunner.query('DROP TABLE `product_barcodes`');
    await queryRunner.query('DROP TABLE `product_units`');
    await queryRunner.query('DROP TABLE `products`');
    await queryRunner.query('DROP TABLE `units`');
    await queryRunner.query('DROP TABLE `manufacturers`');
    await queryRunner.query('DROP TABLE `categories`');
    await queryRunner.query('DROP TABLE `user_branch_access`');
    await queryRunner.query('DROP TABLE `role_permissions`');
    await queryRunner.query('DROP TABLE `user_roles`');
    await queryRunner.query('DROP TABLE `permissions`');
    await queryRunner.query('DROP TABLE `roles`');
    await queryRunner.query('DROP TABLE `users`');
    await queryRunner.query('DROP TABLE `stock_locations`');
    await queryRunner.query('DROP TABLE `warehouses`');
    await queryRunner.query('DROP TABLE `branches`');
    await queryRunner.query('DROP TABLE `organizations`');
  }
}
